export const possible_head_contents: Array<string> = [
  "a software engineer.",
  "a maker.",
  "a builder of all things cool!",
  "a neovim user (btw).",
  "the band spirit!",
  "a fusioneer!",
  "the centerer of divs.",
  "more skilled than yesterday.",
  "a trad coder.",
  "not an outsourced thinker.",
  "a bad frontend dev.",
  "a rock climber!",
  "half-decent at Python.",
  "an up-and-coming Rusteacean!",
  "smarter than the average bear.",
  "doing my own thing.",
  "vibing without AI.",
  "still learning.",
  "working on the puns.",
  "never done with my dotfiles.",
  "in control of my computer.",
  "still at it!",
  "a passable Horn player.",
];
